---
title: "optimize_parameter"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
# matrice D, , calculée pour T deconv et A deconv (= data case)
D_2v2_c <- readRDS("~/Datas/projects/data/extdata/D_2v2_c.rds")
dim(D_2v2_c)

# matrice T, T deconv, il faut prendre la colonne 1 pour avoir le type épi qui sert de data ctrl Penda
EDec2_80p_c_t <- readRDS("~/Datas/projects/data/extdata/EDec2_80p_c_t.rds")
dim(EDec2_80p_c_t)
matrice_T_control <- EDec2_80p_c_t[,1]
length(matrice_T_control)

# matrice T après déconv [,1] = Epithelium: matrice contrôle de penda
T_tum_ref <- readRDS("~/Datas/projects/data/extdata/T_60_tum_rna_c_t.rds")
dim(T_tum_ref$T)

# matrice T tumeur de référence, composée de $T, $g_immune et $g_fibro, sert pour la vignette analyse_deconv
T_60tum_c <- readRDS("~/Datas/projects/data/extdata/T_60_tum_rna_c_t.rds")
dim(T_60tum_c$T)

# matrice A de référence 
A_60p <- readRDS("~/Datas/projects/data/extdata/A_60.rds")
dim(A_60p)

# Matrice A après déconvolution
EDec_80p <- readRDS("~/Datas/projects/data/extdata/EDec_80p.rds")
EDec_80p_a <- EDec_80p$A[,1:60]
dim(EDec_80p_a)
dim(EDec_80p$T)

real_D_matrix <- list(matrix_D = D_2v2_c, T = T_tum_ref)
```

```{r,echo=FALSE}
Penda_dataset = penda::make_dataset_1ctrl(control = matrice_T_control, data_case = D_2v2_c)
data_ctrl = Penda_dataset$data_ctrl
data_case = Penda_dataset$data_case

s_max = 500
L_H_list = penda::compute_lower_and_higher_lists_1ctrl(data_ctrl, s_max = s_max)
L = L_H_list$L
H = L_H_list$H

list1 <- (0:7)/10
list2 <- (80:100)/100
listf <- c(list1,list2)
iterations =  20
dir.create("~/Datas/projects/data/optimize_parameters",recursive = TRUE)
for (threshold in listf){
  penda_res = penda::penda_test_1ctrl(samples = data_case, 
                   iterations =  iterations, 
                   L_H_list =  L_H_list, 
                   threshold = threshold)
  saveRDS(penda_res,file = paste('~/Datas/projects/data/optimize_parameters/res_', threshold, '.RDS',sep=""))
}
```


```{r,echo=TRUE}
# Test all samples
EDec_80p <- readRDS("~/Datas/projects/data/extdata/EDec_80p.rds")
EDec_80p_a <- EDec_80p$A[,1:60]

# Compute CORRELATION HERE 
corr <- RiTMIC::calc_corr(matrix_D = real_D_matrix, matrix_A = EDec_80p_a)
cor_T <- corr$cor_T
T <- corr$matrix_D$T

list1 <- (1:7)/10
list2 <- (80:100)/100
listf <- c(list1,list2)
listf
pvalues <- c(0, 0.00005, 0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.0075, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.15, 0.2, 0.25,  0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1)
length(pvalues)

compute_1_res_FDR = function(values, genes, genes_fibro, genes_immune, pval){
  names(values) = stringr::str_c(genes, rep(1:4))
  values = values[!is.na(values)]
  
  genes_dereg = c(values[stringr::str_c(genes_fibro, rep(2))], values[stringr::str_c(genes_immune, rep(3))])
  genes_dereg = genes_dereg[!is.na(genes_dereg)]
  
  TP = sum(genes_dereg > -log10(pval))
  
  FN = length(genes_dereg) - TP
  
  FP =  sum(values > -log10(pval)) - TP
  
  TN =  length(values) - TP - FN - FP
  
  TPR  = TP / (TP + FN)
  FPR = FP / (TN + FP)
  FDR = FP / (FP + TN)
  return(c(TP, FP, TN, FN, FPR, TPR,FDR))
}

for (threshold in listf){
  penda_res <- readRDS(paste('~/Datas/projects/data/optimize_parameters/res_',threshold,'.RDS',sep=""))
  pre_treat_res <- RiTMIC::pre_treat(penda_res = penda_res, patientNumber=5)
  calc_dist_output <- RiTMIC ::calc_dist(pre_treat_output = pre_treat_res, matrix_A = A_60p)
  genes_f <- calc_dist_output$genes
  df <- calc_dist_output$df
  g_fibro = unique(genes_f[genes_f%in%rownames(T$T)[T$g_fibro]])
  g_immune = unique(genes_f[genes_f%in%rownames(T$T)[T$g_immune]])
  
  res_ks = sapply(pvalues, function(x){
  compute_1_res_FDR(df$ks, df$genes, g_fibro, g_immune, x)
  })
  res_st = sapply(pvalues, function(x){
  compute_1_res_FDR(df$student, df$genes, g_fibro, g_immune, x)
  })
  res_kanto = sapply(pvalues, function(x){
  compute_1_res_FDR(df$kanto, df$genes, g_fibro, g_immune, x)
  })
  res_cor = sapply(pvalues, function(x){
  compute_1_res_FDR(abs(as.numeric(cor_T[, 3])), cor_T[, 1], rownames(T$T)[T$g_fibro], rownames(T$T)[T$g_immune], x)})
  # Initialization
  dfTemp = data.frame(pval = as.factor(rep(pvalues)),
                FPR = c(res_ks[5, ], res_st[5, ], res_kanto[5, ], res_cor[5, ]),
                TPR = c(res_ks[6, ], res_st[6, ], res_kanto[6, ], res_cor[6, ]),
                FDR = c(res_ks[7, ], res_st[7, ], res_kanto[7, ], res_cor[7, ]),
                metrique = rep(c("ks", "student", "kanto", "correlation"),each = length(pvalues)))
  saveRDS(dfTemp, file = paste("~/Datas/projects/data/optimize_parameters/df_FDR_",threshold,'.RDS',sep=""))
}
```

```{r,echo=TRUE, label = "Prepare kanto, student and ks plots"}
list1 <- (1:7)/10
list2 <- (80:100)/100
listf <- c(list1,list2)
#Data loading
for (threshold in listf){
  assign('df', readRDS(paste('~/Datas/projects/data/optimize_parameters/df_',threshold,'.RDS',sep="")))
  assign(paste('df_',threshold,sep=''), readRDS(paste('~/Datas/projects/data/optimize_parameters/df_',threshold,'.RDS',sep="")))
}

df <- data.frame(df_0.1,"threshold"=0.1)

list2 <- listf[2:28]
for (threshold in list2){
  assign('tempDF',eval(parse(text = paste('df_',threshold,sep=""))))
  tempDF['threshold'] <- threshold
  df <- rbind(df,tempDF)
}
dim(df)
```

```{r, label = "kanto plot"}
df_kanto <- subset(df,df$metrique == "kanto")
df_kanto$threshold = as.factor(df_kanto$threshold)
df_corr <- subset(df,df$metrique == "correlation" & df$threshold == 0.1)
df_corr$threshold <- "correlation"
df_corr$threshold = as.factor(df_corr$threshold)
df_kanto <- rbind(df_kanto,df_corr)

library(ggplot2)
plot_kanto <- ggplot(df_kanto, aes(x = FPR, y = TPR, color = threshold, group = threshold)) + 
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(title="Kantorovich")

list1 <- c(5,7)/10
list2 <- (80:90)/100
sublist <- c(list1,list2,"correlation")
sub_kanto <- data.frame(subset(df_kanto, df_kanto$threshold == 0.1))
for (thresh in sublist){
  subset_df_kanto <- data.frame(subset(df_kanto, df_kanto$"threshold" == thresh))
  sub_kanto <- rbind (sub_kanto,subset_df_kanto)
}

plot_sub_kanto <- ggplot(sub_kanto, aes(x = FPR, y = TPR, color = threshold, group = threshold)) + 
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(title="Kantorovich")

library("cowplot")
plot_grid(plot_kanto, plot_sub_kanto,
          ncol=2, nrow=1)

```

```{r, label = "Student plot"}
df_student <- subset(df,df$metrique == "student")
df_student$threshold = as.factor(df_student$threshold)
df_student <- rbind(df_student,df_corr)

plot_student <- ggplot(df_student, aes(x = FPR, y = TPR, color = threshold, group = threshold)) + 
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(title="Student")

list1 <- c(5,7)/10
list2 <- (80:90)/100
sublist <- c(list1,list2,"correlation")
sub_student <- data.frame(subset(df_student, df_student$threshold == 0.1))
for (thresh in sublist){
  subset_df_student <- data.frame(subset(df_student, df_student$"threshold" == thresh))
  sub_student <- rbind (sub_student,subset_df_student)
}

plot_sub_student <- ggplot(sub_student, aes(x = FPR, y = TPR, color = threshold, group = threshold)) + 
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(title="Student")

library("cowplot")
plot_grid(plot_student, plot_sub_student,
          ncol=2, nrow=1)
```

```{r, label = "ks plot"}
df_ks <- subset(df,df$metrique == "ks")
df_ks$threshold = as.factor(df_ks$threshold)
df_ks <- rbind(df_ks,df_corr)

plot_ks <- ggplot(df_ks, aes(x = FPR, y = TPR, color = threshold, group = threshold)) + 
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(title="Kolmogorov Smirnov")

list1 <- c(1:7)/10
list2 <- (80:90)/100
listf <- c(list1,list2)
sublist <- c(list1,list2,"correlation")
sub_ks <- data.frame(subset(df_ks, df_ks$threshold == 0.1))
for (thresh in sublist){
  subset_df_ks <- data.frame(subset(df_ks, df_ks$"threshold" == thresh))
  sub_ks <- rbind (sub_ks,subset_df_ks)
}

plot_sub_ks <- ggplot(sub_ks, aes(x = FPR, y = TPR, color = threshold, group = threshold)) + 
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(title="Kolmogorov Smirnov")

library("cowplot")
plot_grid(plot_ks, plot_sub_ks,
          ncol=2, nrow=1)
```


```{r, label="Choose threshold"}
list1 <- (1:7)/10
list2 <- (80:100)/100
listf <- c(list1,list2)
#Data loading
for (threshold in listf){
  assign('df', readRDS(paste('~/Datas/projects/data/optimize_parameters/df_FDR_',threshold,'.RDS',sep="")))
  assign(paste('df_FDR_',threshold,sep=''), readRDS(paste('~/Datas/projects/data/optimize_parameters/df_FDR_',threshold,'.RDS',sep="")))
}
df <- data.frame(df_FDR_0.1,"threshold"=0.1)

list2 <- listf[2:28]
for (threshold in list2){
  assign('tempDF',eval(parse(text = paste('df_FDR_',threshold,sep=""))))
  tempDF['threshold'] <- threshold
  df <- rbind(df,tempDF)
}
dim(df)

choose_threshold_1_ctrl <- function(max_FDR){
  list1 <- c(1:7)/10
  list2 <- (80:100)/100
  listf <- c(list1,list2)
  
  df_choose <- data.frame(threshold= c(), TPR=c(),method=c())
  method_list <- c("ks","student","kanto")
  
  for (threshold in listf){
    for (method in method_list){
      df_method <- subset(df,df$metrique == method & df$'threshold'== threshold)
      true_df <- subset(df_method,df_method$'FPR' > 0 & df_method$'FDR' <= max_FDR & df_method$'TPR' > 0)
      sub_df <- data.frame('threshold' = threshold, TPR = max(true_df$'TPR'), 'method' = method)
      df_choose <- rbind (df_choose,sub_df)
    }
  }
  threshold_by_method <- data.frame(FDR = c(), FPR=c(), threshold = c(), TPR=c(), method = c())
  for (method in method_list){
    sub_df <- subset(df, df$metrique == method)
    sub_df <- data.frame('FDR' = max_FDR, 'FPR' = sub_df[which.max(true_df$'TPR'),"FPR"],'threshold' = sub_df[which.max(true_df$'TPR'),"threshold"], 'TPR' = max(true_df$'TPR'), 'method' = method)
    threshold_by_method <- rbind(threshold_by_method, sub_df)
  }
  return(threshold_by_method)
}

choose_threshold_1_ctrl(0.08)
```
