---
title: "RiTMIC: RegulatIon of Tumor MIcroenvironment Composition"
subtitle: "Increase your RNAseq datasets with a new simulated adapted dataset derivated from yours"
author: "Magali Richard, Clementine Decamps, Florent Chuffart, Daniel Jost, Fabien Quinquis"
contact: 
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
vignette: >
  %\VignetteIndexEntry{simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}


---

```{r echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=TRUE, results="verbatim", dpi=75)
layout(1, respect=TRUE)
```

# Introduction

`RiTMIC` (**R**egulat**I**on of **T**umor **MI**croenvironment **C**omposition) is an open-access R package that simulates the necessary tools to perform `PenDA` analysis, perform analysis and apply visualization tools to the `PenDA` output. Inputs required to `PenDA` are simulated with `simulation` functions.\cr


Cellular proportion distribution in each This  gene deregulation in individual samples compared to a set of reference, control samples. `penda_1ctrl` is an adaptation of this method for a specific case, only one sample as reference. This particular experimental condition causes a loss of power, as long as possible use the classic version of Penda. This tutorial aims at providing to non-expert users basic informations and illustrations on how to run the package.

# Generation of input files for penda analysis

`PenDA` analysis is an open-access R package that detects gene deregulation in individual samples compared to a set of reference, control samples. 

One matrix of gene expression per sample is required to perform. This matrix can be directly used in `PenDA`.

`simulation` has been developed to simulate an increased dataset that fits with your RNAseq gene distribution dataset. This functionality requires the different cell proportions distributions.

## Increase your dataset with a randomized gene expression distribution


