---
title: "obtain cancer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Data

##Loading D matrices 

2*2 simulations

```{r }
D_80p_s = readRDS("~/projects/pipeline_deconv_analysis/data/D_f/D_80p_rna_s.rds")
D_80p_c = readRDS("~/projects/pipeline_deconv_analysis/data/D_f/D_80p_rna_c.rds")
D_80p_s_b = readRDS("~/projects/pipeline_deconv_analysis/data/D_f/D_80p_rna_s_b.rds")
D_80p_c_b = readRDS("~/projects/pipeline_deconv_analysis/data/D_f/D_80p_rna_c_b.rds")

trueD_s =  readRDS( "~/projects/pipeline_deconv_analysis/data/D_f/D_80p_rna_s.rds")[, 1:60]
trueD_c =  readRDS( "~/projects/pipeline_deconv_analysis/data/D_f/D_80p_rna_c.rds")[, 1:60]

```

Loading A and T matrices
```{r }
A_80p = readRDS( "~/projects/pipeline_deconv_analysis/results/deconv/EDec_80p.rds")$A
colnames(A_80p) = 1:80

trueA = readRDS( "~/projects/pipeline_deconv_analysis/data/A/A_60.rds")

T_80p_s = readRDS("~/projects/pipeline_deconv_analysis/results/deconv/EDec2_80p_s.rds" )
T_80p_c = readRDS("~/projects/pipeline_deconv_analysis/results/deconv/EDec2_80p_c.rds" )
T_80p_s_b = readRDS("~/projects/pipeline_deconv_analysis/results/deconv/EDec2_80p_s_b.rds" )
T_80p_c_b = readRDS("~/projects/pipeline_deconv_analysis/results/deconv/EDec2_80p_c_b.rds" )

trueT = readRDS( "~/projects/pipeline_deconv_analysis/data/T/T_rna.rds")
```

#Computing D_cancer

```{r }
D_cancer_80p_s = (D_80p_s - T_80p_s[, c(1, 2, 4)] %*% A_80p[c(1, 2, 4), ]) / rep(A_80p[3, ], each = nrow(D_80p_s))
saveRDS(D_cancer_80p_s, "~/projects/pipeline_deconv_analysis/results/D_cancer/D_cancer_80p_s.rds")

D_cancer_80p_c = (D_80p_c - T_80p_c[, c(1, 2, 4)] %*% A_80p[c(1, 2, 4), ]) / rep(A_80p[3, ], each = nrow(D_80p_c))
saveRDS(D_cancer_80p_c, "~/projects/pipeline_deconv_analysis/results/D_cancer/D_cancer_80p_c.rds")

D_cancer_80p_s_b = (D_80p_s_b - T_80p_s_b[, c(1, 2, 4)] %*% A_80p[c(1, 2, 4), ]) / rep(A_80p[3, ], each = nrow(D_80p_s_b))
saveRDS(D_cancer_80p_s_b, "~/projects/pipeline_deconv_analysis/results/D_cancer/D_cancer_80p_s_b.rds")

D_cancer_80p_c_b = (D_80p_c_b - T_80p_c_b[, c(1, 2, 4)] %*% A_80p[c(1, 2, 4), ]) / rep(A_80p[3, ], each = nrow(D_80p_c_b))
saveRDS(D_cancer_80p_c_b, "~/projects/pipeline_deconv_analysis/results/D_cancer/D_cancer_80p_c_b.rds")

D_test_s = (trueD_s - trueT %*% trueA[c(1, 2, 3), ]) / rep(trueA[4, ], each = nrow(trueD_s))
D_test_c = (trueD_c - trueT %*% trueA[c(1, 2, 3), ]) / rep(trueA[4, ], each = nrow(trueD_c))

saveRDS(D_test_s, "~/projects/pipeline_deconv_analysis/results/D_cancer/D_test_s.rds")
saveRDS(D_test_c, "~/projects/pipeline_deconv_analysis/results/D_cancer/D_test_c.rds")

```

